/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedMessageTestRouteImport } from './routes/_authenticated/message-test/route'
import { Route as AuthenticatedCodeTemplatesRouteImport } from './routes/_authenticated/code-templates/route'
import { Route as AuthenticatedSettingsIndexImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedCodeTemplatesIndexImport } from './routes/_authenticated/code-templates/index'
import { Route as AuthenticatedSettingsVariablesImport } from './routes/_authenticated/settings/variables'
import { Route as AuthenticatedSettingsSpeechImport } from './routes/_authenticated/settings/speech'
import { Route as AuthenticatedSettingsNotificationsImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsLogsImport } from './routes/_authenticated/settings/logs'
import { Route as AuthenticatedSettingsIotImport } from './routes/_authenticated/settings/iot'
import { Route as AuthenticatedSettingsDisplayImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsDataImport } from './routes/_authenticated/settings/data'
import { Route as AuthenticatedSettingsAppearanceImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedMessageTestRecordsImport } from './routes/_authenticated/message-test/records'
import { Route as AuthenticatedMessageTestNewImport } from './routes/_authenticated/message-test/new'
import { Route as AuthenticatedCodeTemplatesTagsImport } from './routes/_authenticated/code-templates/tags'
import { Route as AuthenticatedCloudSpeakerAccuracyTestRouteImport } from './routes/_authenticated/cloud-speaker/accuracy-test/route'
import { Route as AuthenticatedCloudSpeakerAccuracyTestRecordsImport } from './routes/_authenticated/cloud-speaker/accuracy-test/records'
import { Route as AuthenticatedCloudSpeakerAccuracyTestNewImport } from './routes/_authenticated/cloud-speaker/accuracy-test/new'

// Create/Update Routes

const AuthenticatedRouteRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedIndexRoute = AuthenticatedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

const AuthenticatedSettingsRouteRoute = AuthenticatedSettingsRouteImport.update(
  {
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any,
)

const AuthenticatedMessageTestRouteRoute =
  AuthenticatedMessageTestRouteImport.update({
    id: '/message-test',
    path: '/message-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedCodeTemplatesRouteRoute =
  AuthenticatedCodeTemplatesRouteImport.update({
    id: '/code-templates',
    path: '/code-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedSettingsIndexRoute = AuthenticatedSettingsIndexImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any,
)

const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedCodeTemplatesIndexRoute =
  AuthenticatedCodeTemplatesIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCodeTemplatesRouteRoute,
  } as any)

const AuthenticatedSettingsVariablesRoute =
  AuthenticatedSettingsVariablesImport.update({
    id: '/variables',
    path: '/variables',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsSpeechRoute =
  AuthenticatedSettingsSpeechImport.update({
    id: '/speech',
    path: '/speech',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsLogsRoute = AuthenticatedSettingsLogsImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedSettingsRouteRoute,
} as any)

const AuthenticatedSettingsIotRoute = AuthenticatedSettingsIotImport.update({
  id: '/iot',
  path: '/iot',
  getParentRoute: () => AuthenticatedSettingsRouteRoute,
} as any)

const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsDataRoute = AuthenticatedSettingsDataImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AuthenticatedSettingsRouteRoute,
} as any)

const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

const AuthenticatedMessageTestRecordsRoute =
  AuthenticatedMessageTestRecordsImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => AuthenticatedMessageTestRouteRoute,
  } as any)

const AuthenticatedMessageTestNewRoute =
  AuthenticatedMessageTestNewImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedMessageTestRouteRoute,
  } as any)

const AuthenticatedCodeTemplatesTagsRoute =
  AuthenticatedCodeTemplatesTagsImport.update({
    id: '/tags',
    path: '/tags',
    getParentRoute: () => AuthenticatedCodeTemplatesRouteRoute,
  } as any)

const AuthenticatedCloudSpeakerAccuracyTestRouteRoute =
  AuthenticatedCloudSpeakerAccuracyTestRouteImport.update({
    id: '/cloud-speaker/accuracy-test',
    path: '/cloud-speaker/accuracy-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

const AuthenticatedCloudSpeakerAccuracyTestRecordsRoute =
  AuthenticatedCloudSpeakerAccuracyTestRecordsImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => AuthenticatedCloudSpeakerAccuracyTestRouteRoute,
  } as any)

const AuthenticatedCloudSpeakerAccuracyTestNewRoute =
  AuthenticatedCloudSpeakerAccuracyTestNewImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCloudSpeakerAccuracyTestRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/code-templates': {
      id: '/_authenticated/code-templates'
      path: '/code-templates'
      fullPath: '/code-templates'
      preLoaderRoute: typeof AuthenticatedCodeTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/message-test': {
      id: '/_authenticated/message-test'
      path: '/message-test'
      fullPath: '/message-test'
      preLoaderRoute: typeof AuthenticatedMessageTestRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/cloud-speaker/accuracy-test': {
      id: '/_authenticated/cloud-speaker/accuracy-test'
      path: '/cloud-speaker/accuracy-test'
      fullPath: '/cloud-speaker/accuracy-test'
      preLoaderRoute: typeof AuthenticatedCloudSpeakerAccuracyTestRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/code-templates/tags': {
      id: '/_authenticated/code-templates/tags'
      path: '/tags'
      fullPath: '/code-templates/tags'
      preLoaderRoute: typeof AuthenticatedCodeTemplatesTagsImport
      parentRoute: typeof AuthenticatedCodeTemplatesRouteImport
    }
    '/_authenticated/message-test/new': {
      id: '/_authenticated/message-test/new'
      path: '/new'
      fullPath: '/message-test/new'
      preLoaderRoute: typeof AuthenticatedMessageTestNewImport
      parentRoute: typeof AuthenticatedMessageTestRouteImport
    }
    '/_authenticated/message-test/records': {
      id: '/_authenticated/message-test/records'
      path: '/records'
      fullPath: '/message-test/records'
      preLoaderRoute: typeof AuthenticatedMessageTestRecordsImport
      parentRoute: typeof AuthenticatedMessageTestRouteImport
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/data': {
      id: '/_authenticated/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof AuthenticatedSettingsDataImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/iot': {
      id: '/_authenticated/settings/iot'
      path: '/iot'
      fullPath: '/settings/iot'
      preLoaderRoute: typeof AuthenticatedSettingsIotImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/logs': {
      id: '/_authenticated/settings/logs'
      path: '/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof AuthenticatedSettingsLogsImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/speech': {
      id: '/_authenticated/settings/speech'
      path: '/speech'
      fullPath: '/settings/speech'
      preLoaderRoute: typeof AuthenticatedSettingsSpeechImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/settings/variables': {
      id: '/_authenticated/settings/variables'
      path: '/variables'
      fullPath: '/settings/variables'
      preLoaderRoute: typeof AuthenticatedSettingsVariablesImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/code-templates/': {
      id: '/_authenticated/code-templates/'
      path: '/'
      fullPath: '/code-templates/'
      preLoaderRoute: typeof AuthenticatedCodeTemplatesIndexImport
      parentRoute: typeof AuthenticatedCodeTemplatesRouteImport
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexImport
      parentRoute: typeof AuthenticatedSettingsRouteImport
    }
    '/_authenticated/cloud-speaker/accuracy-test/new': {
      id: '/_authenticated/cloud-speaker/accuracy-test/new'
      path: '/new'
      fullPath: '/cloud-speaker/accuracy-test/new'
      preLoaderRoute: typeof AuthenticatedCloudSpeakerAccuracyTestNewImport
      parentRoute: typeof AuthenticatedCloudSpeakerAccuracyTestRouteImport
    }
    '/_authenticated/cloud-speaker/accuracy-test/records': {
      id: '/_authenticated/cloud-speaker/accuracy-test/records'
      path: '/records'
      fullPath: '/cloud-speaker/accuracy-test/records'
      preLoaderRoute: typeof AuthenticatedCloudSpeakerAccuracyTestRecordsImport
      parentRoute: typeof AuthenticatedCloudSpeakerAccuracyTestRouteImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedCodeTemplatesRouteRouteChildren {
  AuthenticatedCodeTemplatesTagsRoute: typeof AuthenticatedCodeTemplatesTagsRoute
  AuthenticatedCodeTemplatesIndexRoute: typeof AuthenticatedCodeTemplatesIndexRoute
}

const AuthenticatedCodeTemplatesRouteRouteChildren: AuthenticatedCodeTemplatesRouteRouteChildren =
  {
    AuthenticatedCodeTemplatesTagsRoute: AuthenticatedCodeTemplatesTagsRoute,
    AuthenticatedCodeTemplatesIndexRoute: AuthenticatedCodeTemplatesIndexRoute,
  }

const AuthenticatedCodeTemplatesRouteRouteWithChildren =
  AuthenticatedCodeTemplatesRouteRoute._addFileChildren(
    AuthenticatedCodeTemplatesRouteRouteChildren,
  )

interface AuthenticatedMessageTestRouteRouteChildren {
  AuthenticatedMessageTestNewRoute: typeof AuthenticatedMessageTestNewRoute
  AuthenticatedMessageTestRecordsRoute: typeof AuthenticatedMessageTestRecordsRoute
}

const AuthenticatedMessageTestRouteRouteChildren: AuthenticatedMessageTestRouteRouteChildren =
  {
    AuthenticatedMessageTestNewRoute: AuthenticatedMessageTestNewRoute,
    AuthenticatedMessageTestRecordsRoute: AuthenticatedMessageTestRecordsRoute,
  }

const AuthenticatedMessageTestRouteRouteWithChildren =
  AuthenticatedMessageTestRouteRoute._addFileChildren(
    AuthenticatedMessageTestRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDataRoute: typeof AuthenticatedSettingsDataRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsIotRoute: typeof AuthenticatedSettingsIotRoute
  AuthenticatedSettingsLogsRoute: typeof AuthenticatedSettingsLogsRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsSpeechRoute: typeof AuthenticatedSettingsSpeechRoute
  AuthenticatedSettingsVariablesRoute: typeof AuthenticatedSettingsVariablesRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDataRoute: AuthenticatedSettingsDataRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsIotRoute: AuthenticatedSettingsIotRoute,
    AuthenticatedSettingsLogsRoute: AuthenticatedSettingsLogsRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsSpeechRoute: AuthenticatedSettingsSpeechRoute,
    AuthenticatedSettingsVariablesRoute: AuthenticatedSettingsVariablesRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedCloudSpeakerAccuracyTestRouteRouteChildren {
  AuthenticatedCloudSpeakerAccuracyTestNewRoute: typeof AuthenticatedCloudSpeakerAccuracyTestNewRoute
  AuthenticatedCloudSpeakerAccuracyTestRecordsRoute: typeof AuthenticatedCloudSpeakerAccuracyTestRecordsRoute
}

const AuthenticatedCloudSpeakerAccuracyTestRouteRouteChildren: AuthenticatedCloudSpeakerAccuracyTestRouteRouteChildren =
  {
    AuthenticatedCloudSpeakerAccuracyTestNewRoute:
      AuthenticatedCloudSpeakerAccuracyTestNewRoute,
    AuthenticatedCloudSpeakerAccuracyTestRecordsRoute:
      AuthenticatedCloudSpeakerAccuracyTestRecordsRoute,
  }

const AuthenticatedCloudSpeakerAccuracyTestRouteRouteWithChildren =
  AuthenticatedCloudSpeakerAccuracyTestRouteRoute._addFileChildren(
    AuthenticatedCloudSpeakerAccuracyTestRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCodeTemplatesRouteRoute: typeof AuthenticatedCodeTemplatesRouteRouteWithChildren
  AuthenticatedMessageTestRouteRoute: typeof AuthenticatedMessageTestRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCloudSpeakerAccuracyTestRouteRoute: typeof AuthenticatedCloudSpeakerAccuracyTestRouteRouteWithChildren
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCodeTemplatesRouteRoute:
    AuthenticatedCodeTemplatesRouteRouteWithChildren,
  AuthenticatedMessageTestRouteRoute:
    AuthenticatedMessageTestRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCloudSpeakerAccuracyTestRouteRoute:
    AuthenticatedCloudSpeakerAccuracyTestRouteRouteWithChildren,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthenticatedRouteRouteWithChildren
  '/code-templates': typeof AuthenticatedCodeTemplatesRouteRouteWithChildren
  '/message-test': typeof AuthenticatedMessageTestRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/cloud-speaker/accuracy-test': typeof AuthenticatedCloudSpeakerAccuracyTestRouteRouteWithChildren
  '/code-templates/tags': typeof AuthenticatedCodeTemplatesTagsRoute
  '/message-test/new': typeof AuthenticatedMessageTestNewRoute
  '/message-test/records': typeof AuthenticatedMessageTestRecordsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/data': typeof AuthenticatedSettingsDataRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/iot': typeof AuthenticatedSettingsIotRoute
  '/settings/logs': typeof AuthenticatedSettingsLogsRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/speech': typeof AuthenticatedSettingsSpeechRoute
  '/settings/variables': typeof AuthenticatedSettingsVariablesRoute
  '/code-templates/': typeof AuthenticatedCodeTemplatesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/cloud-speaker/accuracy-test/new': typeof AuthenticatedCloudSpeakerAccuracyTestNewRoute
  '/cloud-speaker/accuracy-test/records': typeof AuthenticatedCloudSpeakerAccuracyTestRecordsRoute
}

export interface FileRoutesByTo {
  '/message-test': typeof AuthenticatedMessageTestRouteRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/cloud-speaker/accuracy-test': typeof AuthenticatedCloudSpeakerAccuracyTestRouteRouteWithChildren
  '/code-templates/tags': typeof AuthenticatedCodeTemplatesTagsRoute
  '/message-test/new': typeof AuthenticatedMessageTestNewRoute
  '/message-test/records': typeof AuthenticatedMessageTestRecordsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/data': typeof AuthenticatedSettingsDataRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/iot': typeof AuthenticatedSettingsIotRoute
  '/settings/logs': typeof AuthenticatedSettingsLogsRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/speech': typeof AuthenticatedSettingsSpeechRoute
  '/settings/variables': typeof AuthenticatedSettingsVariablesRoute
  '/code-templates': typeof AuthenticatedCodeTemplatesIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/cloud-speaker/accuracy-test/new': typeof AuthenticatedCloudSpeakerAccuracyTestNewRoute
  '/cloud-speaker/accuracy-test/records': typeof AuthenticatedCloudSpeakerAccuracyTestRecordsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/code-templates': typeof AuthenticatedCodeTemplatesRouteRouteWithChildren
  '/_authenticated/message-test': typeof AuthenticatedMessageTestRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/cloud-speaker/accuracy-test': typeof AuthenticatedCloudSpeakerAccuracyTestRouteRouteWithChildren
  '/_authenticated/code-templates/tags': typeof AuthenticatedCodeTemplatesTagsRoute
  '/_authenticated/message-test/new': typeof AuthenticatedMessageTestNewRoute
  '/_authenticated/message-test/records': typeof AuthenticatedMessageTestRecordsRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/data': typeof AuthenticatedSettingsDataRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/iot': typeof AuthenticatedSettingsIotRoute
  '/_authenticated/settings/logs': typeof AuthenticatedSettingsLogsRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/speech': typeof AuthenticatedSettingsSpeechRoute
  '/_authenticated/settings/variables': typeof AuthenticatedSettingsVariablesRoute
  '/_authenticated/code-templates/': typeof AuthenticatedCodeTemplatesIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/cloud-speaker/accuracy-test/new': typeof AuthenticatedCloudSpeakerAccuracyTestNewRoute
  '/_authenticated/cloud-speaker/accuracy-test/records': typeof AuthenticatedCloudSpeakerAccuracyTestRecordsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/code-templates'
    | '/message-test'
    | '/settings'
    | '/'
    | '/cloud-speaker/accuracy-test'
    | '/code-templates/tags'
    | '/message-test/new'
    | '/message-test/records'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/data'
    | '/settings/display'
    | '/settings/iot'
    | '/settings/logs'
    | '/settings/notifications'
    | '/settings/speech'
    | '/settings/variables'
    | '/code-templates/'
    | '/help-center'
    | '/settings/'
    | '/cloud-speaker/accuracy-test/new'
    | '/cloud-speaker/accuracy-test/records'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/message-test'
    | '/'
    | '/cloud-speaker/accuracy-test'
    | '/code-templates/tags'
    | '/message-test/new'
    | '/message-test/records'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/data'
    | '/settings/display'
    | '/settings/iot'
    | '/settings/logs'
    | '/settings/notifications'
    | '/settings/speech'
    | '/settings/variables'
    | '/code-templates'
    | '/help-center'
    | '/settings'
    | '/cloud-speaker/accuracy-test/new'
    | '/cloud-speaker/accuracy-test/records'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/code-templates'
    | '/_authenticated/message-test'
    | '/_authenticated/settings'
    | '/_authenticated/'
    | '/_authenticated/cloud-speaker/accuracy-test'
    | '/_authenticated/code-templates/tags'
    | '/_authenticated/message-test/new'
    | '/_authenticated/message-test/records'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/data'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/iot'
    | '/_authenticated/settings/logs'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/speech'
    | '/_authenticated/settings/variables'
    | '/_authenticated/code-templates/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/cloud-speaker/accuracy-test/new'
    | '/_authenticated/cloud-speaker/accuracy-test/records'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_authenticated"
      ]
    },
    "/_authenticated": {
      "filePath": "_authenticated/route.tsx",
      "children": [
        "/_authenticated/code-templates",
        "/_authenticated/message-test",
        "/_authenticated/settings",
        "/_authenticated/",
        "/_authenticated/cloud-speaker/accuracy-test",
        "/_authenticated/help-center/"
      ]
    },
    "/_authenticated/code-templates": {
      "filePath": "_authenticated/code-templates/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/code-templates/tags",
        "/_authenticated/code-templates/"
      ]
    },
    "/_authenticated/message-test": {
      "filePath": "_authenticated/message-test/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/message-test/new",
        "/_authenticated/message-test/records"
      ]
    },
    "/_authenticated/settings": {
      "filePath": "_authenticated/settings/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/settings/account",
        "/_authenticated/settings/appearance",
        "/_authenticated/settings/data",
        "/_authenticated/settings/display",
        "/_authenticated/settings/iot",
        "/_authenticated/settings/logs",
        "/_authenticated/settings/notifications",
        "/_authenticated/settings/speech",
        "/_authenticated/settings/variables",
        "/_authenticated/settings/"
      ]
    },
    "/_authenticated/": {
      "filePath": "_authenticated/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/cloud-speaker/accuracy-test": {
      "filePath": "_authenticated/cloud-speaker/accuracy-test/route.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/cloud-speaker/accuracy-test/new",
        "/_authenticated/cloud-speaker/accuracy-test/records"
      ]
    },
    "/_authenticated/code-templates/tags": {
      "filePath": "_authenticated/code-templates/tags.tsx",
      "parent": "/_authenticated/code-templates"
    },
    "/_authenticated/message-test/new": {
      "filePath": "_authenticated/message-test/new.tsx",
      "parent": "/_authenticated/message-test"
    },
    "/_authenticated/message-test/records": {
      "filePath": "_authenticated/message-test/records.tsx",
      "parent": "/_authenticated/message-test"
    },
    "/_authenticated/settings/account": {
      "filePath": "_authenticated/settings/account.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/appearance": {
      "filePath": "_authenticated/settings/appearance.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/data": {
      "filePath": "_authenticated/settings/data.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/display": {
      "filePath": "_authenticated/settings/display.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/iot": {
      "filePath": "_authenticated/settings/iot.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/logs": {
      "filePath": "_authenticated/settings/logs.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/notifications": {
      "filePath": "_authenticated/settings/notifications.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/speech": {
      "filePath": "_authenticated/settings/speech.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/settings/variables": {
      "filePath": "_authenticated/settings/variables.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/code-templates/": {
      "filePath": "_authenticated/code-templates/index.tsx",
      "parent": "/_authenticated/code-templates"
    },
    "/_authenticated/help-center/": {
      "filePath": "_authenticated/help-center/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/settings/": {
      "filePath": "_authenticated/settings/index.tsx",
      "parent": "/_authenticated/settings"
    },
    "/_authenticated/cloud-speaker/accuracy-test/new": {
      "filePath": "_authenticated/cloud-speaker/accuracy-test/new.tsx",
      "parent": "/_authenticated/cloud-speaker/accuracy-test"
    },
    "/_authenticated/cloud-speaker/accuracy-test/records": {
      "filePath": "_authenticated/cloud-speaker/accuracy-test/records.tsx",
      "parent": "/_authenticated/cloud-speaker/accuracy-test"
    }
  }
}
ROUTE_MANIFEST_END */
